### ISSUE TITLE
Select storage path

### ISSUE THREAD

**Issue by fabianrost84** [dkim0419/SoundRecorder#31] opened 2015-12-18 22:09 UTC
What keeps me from using this app is that it safes recordings to the internal memory of my Motorola Moto E. The reason seems to be that `Environment.getExternalStorageDirectory()` points to the internal memory instead of the SD card for the Moto E. My internal memory is too small to store all my recordings. 

It seems to me that the only general solution to my problem to make the storate path selectable by the user. Is it planned to implement this? 

It also seems to be similar to the way the ownCloud Android app handles the storage of files (see https://github.com/owncloud/android/issues/10). There they state the beta version of ownCloud now offers an option to select the storage path. Maybe one could learn from there.

I'm willing to help on this, but I'm not much of an Android developer, unfortunately.

**Comment by jospoortvliet** [comment] 2016-04-25 09:48
Duplicate of https://github.com/owncloud/android/issues/10 ;-)

**Comment by fbnrst** [comment] 2017-05-24 21:08
I changed my phone and do not need this anymore. In the spirit of keeping the app simple, I think this feature is not essential, so I close this one.

**Closed by fbnrst** 2017-05-24 21:08 UTC
