### ISSUE TITLE
Pause button is not working

### ISSUE THREAD

**Issue by tandins** [dkim0419/SoundRecorder#61] opened 2016-11-21 06:47 UTC
Is pause button not worked?

**Comment by andrewgaul** [comment] 2016-11-21 21:36
Can you give some more background?  I can play back a recording then pause and resume it.

**Comment by github-user-1** [comment] 2016-12-06 12:21
I think this is regarding the Pause-Button missing during recording - that's the one at least that I'm missing. In some cases it would be great to pause the recording and then resume it (instead of having two or more recordings in the end when using the stop button).
Would be just great to have it (so two buttons while recording - pause and stop).

**Comment by fbnrst** [comment] 2017-05-24 21:10
duplicate of #17, please close.

**Closed** 2017-05-25 01:06 UTC
